# Generated by Django 4.2.3 on 2023-07-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='state',
            field=models.CharField(blank=True, choices=[('r', 'Reservado'), ('a', 'Activo'), ('m', 'Mantenimiento')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='editorial',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
