# Generated by Django 4.2.3 on 2023-07-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_state_alter_book_editorial_alter_book_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(blank=True, choices=[('P', 'Pasta'), ('D', 'Digital')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='state',
            field=models.CharField(blank=True, choices=[('r', 'Reservado'), ('m', 'Mantenimiento'), ('a', 'Activo')], default='a', max_length=1),
        ),
    ]
